package com.example.storeapp.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF845416)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDCBC)
val onPrimaryContainerLight = Color(0xFF2C1700)
val secondaryLight = Color(0xFF725A42)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFEDDBE)
val onSecondaryContainerLight = Color(0xFF291805)
val tertiaryLight = Color(0xFF57633B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDAE9B6)
val onTertiaryContainerLight = Color(0xFF151F01)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F4)
val onBackgroundLight = Color(0xFF211A14)
val surfaceLight = Color(0xFFFFF8F4)
val onSurfaceLight = Color(0xFF211A14)
val surfaceVariantLight = Color(0xFFF1DFD0)
val onSurfaceVariantLight = Color(0xFF50453A)
val outlineLight = Color(0xFF837568)
val outlineVariantLight = Color(0xFFD5C4B5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF372F28)
val inverseOnSurfaceLight = Color(0xFFFDEEE3)
val inversePrimaryLight = Color(0xFFFBBA73)
val surfaceDimLight = Color(0xFFE6D8CC)
val surfaceBrightLight = Color(0xFFFFF8F4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E7)
val surfaceContainerLight = Color(0xFFFAEBE0)
val surfaceContainerHighLight = Color(0xFFF4E6DA)
val surfaceContainerHighestLight = Color(0xFFEEE0D5)

val primaryDark = Color(0xFFFBBA73)
val onPrimaryDark = Color(0xFF492900)
val primaryContainerDark = Color(0xFF683D00)
val onPrimaryContainerDark = Color(0xFFFFDCBC)
val secondaryDark = Color(0xFFE0C1A3)
val onSecondaryDark = Color(0xFF402D18)
val secondaryContainerDark = Color(0xFF58432C)
val onSecondaryContainerDark = Color(0xFFFEDDBE)
val tertiaryDark = Color(0xFFBECC9B)
val onTertiaryDark = Color(0xFF293411)
val tertiaryContainerDark = Color(0xFF3F4B25)
val onTertiaryContainerDark = Color(0xFFDAE9B6)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF19120C)
val onBackgroundDark = Color(0xFFEEE0D5)
val surfaceDark = Color(0xFF19120C)
val onSurfaceDark = Color(0xFFEEE0D5)
val surfaceVariantDark = Color(0xFF50453A)
val onSurfaceVariantDark = Color(0xFFD5C4B5)
val outlineDark = Color(0xFF9D8E81)
val outlineVariantDark = Color(0xFF50453A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEEE0D5)
val inverseOnSurfaceDark = Color(0xFF372F28)
val inversePrimaryDark = Color(0xFF845416)
val surfaceDimDark = Color(0xFF19120C)
val surfaceBrightDark = Color(0xFF403830)
val surfaceContainerLowestDark = Color(0xFF130D07)
val surfaceContainerLowDark = Color(0xFF211A14)
val surfaceContainerDark = Color(0xFF251E17)
val surfaceContainerHighDark = Color(0xFF302921)
val surfaceContainerHighestDark = Color(0xFF3B332C)
val colorRating = Color(0xFFffbe08)




